SABAR="../libjpeg/cdjpeg.c ../libjpeg/jaricom.c ../libjpeg/jcapimin.c ../libjpeg/jcapistd.c ../libjpeg/jcarith.c ../libjpeg/jccoefct.c ../libjpeg/jccolor.c ../libjpeg/jcdctmgr.c ../libjpeg/jchuff.c ../libjpeg/jcinit.c ../libjpeg/jcmainct.c ../libjpeg/jcmarker.c ../libjpeg/jcmaster.c ../libjpeg/jcomapi.c ../libjpeg/jcparam.c ../libjpeg/jcprepct.c ../libjpeg/jcsample.c ../libjpeg/jctrans.c ../libjpeg/jdapimin.c ../libjpeg/jdapistd.c ../libjpeg/jdarith.c ../libjpeg/jdatadst.c ../libjpeg/jdatasrc.c ../libjpeg/jdcoefct.c ../libjpeg/jdcolor.c ../libjpeg/jddctmgr.c ../libjpeg/jdhuff.c ../libjpeg/jdinput.c ../libjpeg/jdmainct.c ../libjpeg/jdmarker.c ../libjpeg/jdmaster.c ../libjpeg/jdmerge.c ../libjpeg/jdpostct.c ../libjpeg/jdsample.c ../libjpeg/jdtrans.c ../libjpeg/jerror.c ../libjpeg/jfdctflt.c ../libjpeg/jfdctfst.c ../libjpeg/jfdctint.c ../libjpeg/jidctflt.c ../libjpeg/jidctfst.c ../libjpeg/jidctint.c ../libjpeg/jmemmgr.c ../libjpeg/jmemnobs.c ../libjpeg/jquant1.c ../libjpeg/jquant2.c ../libjpeg/jutils.c ../libjpeg/rdbmp.c ../libjpeg/rdcolmap.c ../libjpeg/rdgif.c ../libjpeg/rdppm.c ../libjpeg/rdrle.c ../libjpeg/rdswitch.c ../libjpeg/rdtarga.c ../libjpeg/transupp.c ../libjpeg/wrbmp.c ../libjpeg/wrgif.c ../libjpeg/wrppm.c ../libjpeg/wrrle.c ../libjpeg/wrtarga.c"
# SABAR=""
SUBUR="../../webp-converter/libwebp/src/\dec,dsp,demux,enc,mux,utils}/*.c ../../webp-converter/libwebp/imageio/*.c  ../../webp-converter/libwebp/sharpyuv/*.c"
echo $SABAR
# emcc -O3 -Wall -g3 -sWASM=1 -sSIDE_MODULE $SABAR -I ../libjpeg/ -L ../libjpeg/build/ -o sabar.wasm
# emcc -O3 -Wall -g3 -sWASM=1 -sSIDE_MODULE ../../webp-converter/libwebp/src/{dec,dsp,demux,enc,mux,utils}/*.c ../../webp-converter/libwebp/imageio/*.c  ../../webp-converter/libwebp/sharpyuv/*.c \
#  -I ../../webp-converter/libwebp/ -I ../../webp-converter/libwebp/src/ -o libwebp.wasm
# emcc -O3 -Wall -g3 -sWASM=1 -sEXPORTED_RUNTIME_METHODS=cwrap -sEXPORTED_FUNCTIONS=_main,_guessFormat,_dump,_alloc,_falloc,_malloc,_convert \
#      test.cpp 
#     ../../webp-converter/libwebp/src/{dec,dsp,demux,enc,mux,utils,webp}/*.c ../../webp-converter/libwebp/imageio/*.c  ../../webp-converter/libwebp/sharpyuv/*.c \
#     ../libjpeg/cdjpeg.c ../libjpeg/jaricom.c ../libjpeg/jcapimin.c ../libjpeg/jcapistd.c ../libjpeg/jcarith.c ../libjpeg/jccoefct.c ../libjpeg/jccolor.c ../libjpeg/jcdctmgr.c ../libjpeg/jchuff.c ../libjpeg/jcinit.c ../libjpeg/jcmainct.c ../libjpeg/jcmarker.c ../libjpeg/jcmaster.c ../libjpeg/jcomapi.c ../libjpeg/jcparam.c ../libjpeg/jcprepct.c ../libjpeg/jcsample.c ../libjpeg/jctrans.c ../libjpeg/jdapimin.c ../libjpeg/jdapistd.c ../libjpeg/jdarith.c ../libjpeg/jdatadst.c ../libjpeg/jdatasrc.c ../libjpeg/jdcoefct.c ../libjpeg/jdcolor.c ../libjpeg/jddctmgr.c ../libjpeg/jdhuff.c ../libjpeg/jdinput.c ../libjpeg/jdmainct.c ../libjpeg/jdmarker.c ../libjpeg/jdmaster.c ../libjpeg/jdmerge.c ../libjpeg/jdpostct.c ../libjpeg/jdsample.c ../libjpeg/jdtrans.c ../libjpeg/jerror.c ../libjpeg/jfdctflt.c ../libjpeg/jfdctfst.c ../libjpeg/jfdctint.c ../libjpeg/jidctflt.c ../libjpeg/jidctfst.c ../libjpeg/jidctint.c ../libjpeg/jmemmgr.c ../libjpeg/jmemnobs.c ../libjpeg/jquant1.c ../libjpeg/jquant2.c ../libjpeg/jutils.c ../libjpeg/rdbmp.c ../libjpeg/rdcolmap.c ../libjpeg/rdgif.c ../libjpeg/rdppm.c ../libjpeg/rdrle.c ../libjpeg/rdswitch.c ../libjpeg/rdtarga.c ../libjpeg/transupp.c ../libjpeg/wrbmp.c ../libjpeg/wrgif.c ../libjpeg/wrppm.c ../libjpeg/wrrle.c ../libjpeg/wrtarga.c \
#     -I ../../webp-converter/libwebp/ -I ../../webp-converter/libwebp/src/ -I ../../webp-converter/libwebp/src/webp/types.h -I ../../webp-converter/libwebp/imageio/ -I ../../webp-converter/libwebp/sharpyuv/  -I ../libjpeg/ -L ../libjpeg/ -L ../../webp-converter/libwebp/ -L ../../webp-converter/libwebp/src/ -L ../../webp-converter/libwebp/src/webp/ -L ../../webp-converter/libwebp/imageio/ -L ../../webp-converter/libwebp/sharpyuv/ -L ../libjpeg/build/ 
    



emcc -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_NAME=\"'ModuleEncode'\" -o encode.js -O3 -Wall -g3 -sWASM=1 -sEXPORTED_RUNTIME_METHODS=cwrap -sEXPORTED_FUNCTIONS=_main,_dump,_alloc,_malloc,_encodeRGBA,_falloc  encode.cpp \
   ../../webp-converter/libwebp/src/{dec,dsp,demux,enc,mux,utils}/*.c ../../webp-converter/libwebp/imageio/*.c  ../../webp-converter/libwebp/sharpyuv/*.c \
  -I ../../webp-converter/libwebp/src/dec/ -I ../../webp-converter/libwebp/src/dsp/ -I ../../webp-converter/libwebp/src/demux/ -I ../../webp-converter/libwebp/src/enc/ -I ../../webp-converter/libwebp/src/mux/ -I ../../webp-converter/libwebp/src/utils/  -I ../../webp-converter/libwebp/sharpyuv/ -I ../../webp-converter/libwebp/ -I ../../webp-converter/libwebp/src/ -I ../libjpeg/ \
  -L ../../webp-converter/libwebp/src/dec/ -L ../../webp-converter/libwebp/src/dsp/ -L ../../webp-converter/libwebp/src/demux/ -L ../../webp-converter/libwebp/src/enc/ -L ../../webp-converter/libwebp/src/mux/ -L ../../webp-converter/libwebp/src/utils/  -L ../../webp-converter/libwebp/sharpyuv/ -L ../../webp-converter/libwebp/ -L ../../webp-converter/libwebp/src/ -L /usr/local/lib/

# emcc -O3 -Wall -g3 -sWASM=1 -sEXPORTED_RUNTIME_METHODS=cwrap -sEXPORTED_FUNCTIONS=_main,_allocateBuffer,_dump,_alloc,_webpFree,_encodeRGBA encode.cpp -I ../../webp-converter/libwebp/src/